# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.projectDir : '%env(resolve:APP_PROJECTDIR)%'
    app.imgDir : '%env(resolve:IMG_DIR)%'
    app.domain.img : '%env(resolve:DOMAIN_IMG)%'


    amazon.s3.key:     '%env(resolve:AWS_KEY)%'
    amazon.s3.secret:  '%env(resolve:AWS_SECRET)%'
    amazon.s3.region:  '%env(resolve:AWS_REGION)%'
    amazon.s3.bucket:  '%env(resolve:AWS_BUCKET)%'
    amazon.s3.version: '%env(resolve:AWS_VERSION)%'
        
    #CloudFront
    amazon.s3.bucket.front:  '%env(resolve:AWS_BUCKET_FRONT)%'


services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Controller\Admin\PostsCrudController:
        arguments:
            $projectDir: '%kernel.project_dir%'

    App\Controller\Admin\ParagraphPostsCrudController:
        arguments:
            $projectDir: '%kernel.project_dir%'

